parameters:
    activity_collector_class: AppBundle\EventListener\ActivityCollector

services:
    activity_collector:
        arguments: [@app.activity_changes]
        class: %activity_collector_class%
        tags:
            - { name: doctrine.orm.entity_listener }
