imports:
    - { resource: "@AppBundle/Resources/config/filters.yml" }
    - { resource: "@AppBundle/Resources/config/form.yml" }
    - { resource: "@AppBundle/Resources/config/listeners.yml" }
    - { resource: "@AppBundle/Resources/config/twig.yml" }
    - { resource: "@AppBundle/Resources/config/voters.yml" }

# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    project_filter_class: AppBundle\Security\Filter\ProjectFilter
    project_code_converter_class: AppBundle\Utils\ProjectCodeConverter
    issue_param_converter_class: AppBundle\Request\ParamConverter\IssueConverter
    issue_code_converter_class: AppBundle\Utils\IssueCodeConverter
    issue_code_generator_class: AppBundle\Utils\IssueCodeGenerator
    issue_filter_class: AppBundle\Security\Filter\IssueFilter
    comment_tree_class: AppBundle\Templating\Comment\CommentTree
    activity_changes_class: AppBundle\Utils\ActivityChanges
    activity_filter_class: AppBundle\Security\Filter\ActivityFilter
    activity_extractor_factory_class: AppBundle\Utils\ActivityExtractorFactory
    activity_motification_class: AppBundle\Utils\ActivityNotification

services:
    app.project_code_converter:
        class:      %project_code_converter_class%

    app.request.params.issue_converter:
        arguments: [@app.issue_code_converter, @doctrine]
        class:      %issue_param_converter_class%
        tags:
            - { name: request.param_converter }

    app.issue_code_converter:
        arguments: [@doctrine.orm.entity_manager]
        class:      %issue_code_converter_class%

    app.project_code_generator:
        arguments: [@doctrine.orm.entity_manager]
        class:      %issue_code_generator_class%

    app.templating.comment_tree:
        class:      %comment_tree_class%

    app.activity_changes:
        arguments: [@security.token_storage]
        class: %activity_changes_class%
        tags:
            - { name: doctrine.orm.entity_listener }

    app.activity_extractor_factory:
        arguments: [@doctrine, @app.security.activity_filter]
        class:      %activity_extractor_factory_class%

    app.activity_motification:
        arguments: [@templating, @mailer, %email_from%]
        class:      %activity_motification_class%
        tags:
            - { name: kernel.event_listener, event: app.events.activity_created, method: onActivityCreated }
