# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    user_voter_class: AppBundle\Security\Authorization\Voter\UserVoter
    project_voter_class: AppBundle\Security\Authorization\Voter\ProjectVoter
    project_filter_class: AppBundle\Security\Filter\ProjectFilter
    project_code_converter_class: AppBundle\Utils\ProjectCodeConverter
    project_type_class: AppBundle\Form\ProjectType
    issue_param_converter_class: AppBundle\Request\ParamConverter\IssueConverter
    issue_code_converter_class: AppBundle\Utils\IssueCodeConverter
    app_twig_extension_class: AppBundle\Twig\AppExtension
    issue_voter_class: AppBundle\Security\Authorization\Voter\IssueVoter
    issue_code_generator_class: AppBundle\Utils\IssueCodeGenerator
    issue_type_class: AppBundle\Form\IssueType
    issue_filter_class: AppBundle\Security\Filter\IssueFilter
    entity_hidden_type_class: AppBundle\Form\EntityHiddenType
    comment_tree_class: AppBundle\Templating\Comment\CommentTree

services:
    security.access.user_voter:
        arguments: [@security.token_storage, @security.access.role_hierarchy_voter]
        class:      %user_voter_class%
        public:     false
        tags:
            - { name: security.voter }

    security.access.project_voter:
        arguments: [@security.token_storage, @security.access.role_hierarchy_voter]
        class:      %project_voter_class%
        public:     false
        tags:
            - { name: security.voter }

    app.security.project_filter:
        arguments: [@security.token_storage]
        class:      %project_filter_class%

    app.project_code_converter:
        class:      %project_code_converter_class%

    app.form.type.project:
        arguments: [@app.project_code_converter]
        class:      %project_type_class%
        tags:
            - { name: form.type, alias: appbundle_project }

    app.request.params.issue_converter:
        arguments: [@app.issue_code_converter, @doctrine]
        class:      %issue_param_converter_class%
        tags:
            - { name: request.param_converter }

    app.issue_code_converter:
        arguments: [@doctrine.orm.entity_manager]
        class:      %issue_code_converter_class%

    app.twig_extension:
        arguments: [@app.issue_code_converter, @app.templating.comment_tree]
        class:      %app_twig_extension_class%
        public:     false
        tags:
            - { name: twig.extension }

    security.access.issue_voter:
        arguments: [@security.token_storage, @security.access.role_hierarchy_voter]
        class:      %issue_voter_class%
        public:     false
        tags:
            - { name: security.voter }

    app.project_code_generator:
        arguments: [@doctrine.orm.entity_manager]
        class:      %issue_code_generator_class%

    app.form.type.issue:
        arguments: [@app.project_code_generator, @doctrine.orm.entity_manager]
        class:      %issue_type_class%
        tags:
            - { name: form.type, alias: appbundle_issue }

    app.security.issue_filter:
        arguments: [@security.token_storage]
        class:      %issue_filter_class%

    app.form.type.entity_hidden:
        arguments: [@doctrine.orm.entity_manager]
        class:      %entity_hidden_type_class%
        tags:
            - { name: form.type, alias: app_entity_hidden }

    app.templating.comment_tree:
        class:      %comment_tree_class%
        tags:
            - { name: form.type, alias: app_entity_hidden }
