# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    user_voter_class: AppBundle\Security\Authorization\Voter\UserVoter
    project_voter_class: AppBundle\Security\Authorization\Voter\ProjectVoter
    project_filter_class: AppBundle\Security\Filter\ProjectFilter
    name_converter_class: AppBundle\Utils\NameConverter

services:
    security.access.user_voter:
        arguments: [@security.token_storage, @security.access.role_hierarchy_voter]
        class:      %user_voter_class%
        public:     false
        tags:
            - { name: security.voter }

    security.access.project_voter:
        arguments: [@security.token_storage, @security.access.role_hierarchy_voter]
        class:      %project_voter_class%
        public:     false
        tags:
            - { name: security.voter }

    app.project_filter:
        arguments: [@security.token_storage]
        class:      %project_filter_class%

    app.name_converter:
        class:      %name_converter_class%
