# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    user_voter_class: AppBundle\Security\Authorization\Voter\UserVoter

services:
    security.access.post_voter:
        arguments: [@security.token_storage, @security.access.role_hierarchy_voter]
        class:      %user_voter_class%
        public:     false
        tags:
            - { name: security.voter }
