<?php

namespace AppBundle\Entity;

/**
 * IssueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCodeAndProjectCode($code, $projectCode)
    {
        return $this->createQueryBuilder('i')
            ->innerJoin('i.project', 'p')
            ->where('p.code = :projectCode')
            ->andWhere('i.code = :issueCode')
            ->setParameter('projectCode', $code)
            ->setParameter('issueCode', $projectCode)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
