<?php

namespace AppBundle\Entity;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $code
     * @return null|Project
     */
    public function findOneByCode($code)
    {
        return $this->findOneBy(['code' => $code]);
    }
}
