<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository
{
    /**
     * @var array
     */
    private $entities;

    /**
     * @return Role|null
     */
    public function findOperatorRole()
    {
        return $this->findByRole('ROLE_OPERATOR');
    }

    /**
     * @return Role|null
     */
    public function findManagerRole()
    {
        return $this->findByRole('ROLE_MANAGER');
    }

    /**
     * @return Role|null
     */
    public function findAdminRole()
    {
        return $this->findByRole('ROLE_ADMIN');
    }

    /**
     * @param $role
     * @return null|Role
     */
    private function findByRole($role)
    {
        if (empty($this->entities)) {
            $this->entities = $this->findAll();
        }
        foreach ($this->entities as $entity) {
            /** @var Role $entity */
            if ($entity->getRole() === $role) {
                return $entity;
            }
        }
    }
}
